name: IMAGDressing
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.12.2=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
    - absl-py==2.3.1
    - accelerate==0.29.3
    - addict==2.4.0
    - aiofiles==23.2.1
    - aiohttp==3.9.5
    - aiosignal==1.3.1
    - albucore==0.0.17
    - albumentations==1.4.18
    - aliyun-python-sdk-core==2.16.0
    - aliyun-python-sdk-kms==2.16.5
    - annotated-doc==0.0.4
    - annotated-types==0.6.0
    - anyio==4.5.2
    - astunparse==1.6.3
    - async-timeout==4.0.3
    - attrs==23.2.0
    - bitsandbytes==0.43.1
    - certifi==2024.2.2
    - cffi==1.17.1
    - charset-normalizer==3.3.2
    - click==8.1.8
    - coloredlogs==15.0.1
    - contourpy==1.1.1
    - controlnet-aux==0.0.10
    - crcmod==1.7
    - cryptography==46.0.3
    - cycler==0.12.1
    - cython==3.2.4
    - datasets==2.13.0
    - deepspeed==0.14.1
    - diffusers==0.24.0
    - dill==0.3.6
    - easydict==1.13
    - einops==0.7.0
    - eval-type-backport==0.3.1
    - exceptiongroup==1.3.1
    - fastapi==0.124.4
    - ffmpy==0.5.0
    - filelock==3.9.0
    - flatbuffers==25.12.19
    - fonttools==4.57.0
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gast==0.4.0
    - google-auth==2.47.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - gradio==4.44.1
    - gradio-client==1.3.0
    - grpcio==1.70.0
    - h11==0.16.0
    - h5py==3.11.0
    - hjson==3.1.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.22.2
    - humanfriendly==10.0
    - idna==3.7
    - imageio==2.35.1
    - importlib-metadata==7.1.0
    - importlib-resources==6.4.5
    - insightface==0.7.3
    - jinja2==3.1.2
    - jmespath==0.10.0
    - joblib==1.4.2
    - keras==2.13.1
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - libclang==18.1.1
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.7.5
    - mdurl==0.1.2
    - mmcv==1.7.2
    - mmdet==3.3.0
    - modelscope==1.9.2
    - mpmath==1.3.0
    - multidict==6.0.5
    - multiprocess==0.70.14
    - networkx==3.1
    - ninja==1.11.1.1
    - numpy==1.24.3
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==9.1.0.70
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.9.86
    - nvidia-nvtx-cu11==11.8.86
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.3.1
    - onnx==1.17.0
    - onnxruntime-gpu==1.17.1
    - opencv-python-headless==4.12.0.88
    - opt-einsum==3.4.0
    - orjson==3.10.15
    - oss2==2.19.1
    - packaging==24.0
    - pandas==2.0.3
    - pillow==10.2.0
    - platformdirs==4.3.6
    - prettytable==3.11.0
    - protobuf==4.25.8
    - psutil==5.9.8
    - py-cpuinfo==9.0.0
    - pyarrow==15.0.2
    - pyarrow-hotfix==0.6
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pycocotools==2.0.7
    - pycparser==2.23
    - pycryptodome==3.23.0
    - pydantic==2.7.0
    - pydantic-core==2.18.1
    - pydub==0.25.1
    - pygments==2.19.2
    - pynvml==11.5.0
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.20
    - pytz==2024.1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - regex==2024.4.16
    - requests==2.31.0
    - requests-oauthlib==2.0.0
    - rich==14.2.0
    - rsa==4.9.1
    - ruff==0.14.11
    - safetensors==0.4.3
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - semantic-version==2.10.0
    - shapely==2.0.7
    - shellingham==1.5.4
    - simplejson==3.20.2
    - six==1.16.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - starlette==0.44.0
    - sympy==1.12
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.13.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.4.0
    - terminaltables==3.1.10
    - threadpoolctl==3.5.0
    - tifffile==2023.7.10
    - timm==1.0.24
    - tokenizers==0.19.1
    - tomli==2.4.0
    - tomlkit==0.12.0
    - torch==2.4.1+cu118
    - torchaudio==2.4.1+cu118
    - torchvision==0.19.1+cu118
    - tqdm==4.66.2
    - transformers==4.40.0
    - triton==3.0.0
    - typer==0.20.1
    - typing-extensions==4.13.2
    - tzdata==2024.1
    - urllib3==2.2.1
    - uvicorn==0.33.0
    - wcwidth==0.2.14
    - websockets==12.0
    - werkzeug==3.0.6
    - wrapt==2.0.1
    - xxhash==3.4.1
    - yapf==0.43.0
    - yarl==1.9.4
    - zipp==3.18.1
prefix: /root/miniconda3/envs/IMAGDressing
